name: expandable
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 1.0.0+1
author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ">=1.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
