name: expandable
description: A Flutter widget that can be expanded or collapsed by clicking on a header or an icon.
version: 2.2.3
author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage: https://github.com/aryzhov/flutter-expandable

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 < 3.0.0"
  flutter: "^1.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
